author:
  name: Juan Diego Coronel Montesinos
baseURL: "http://localhost:1313/"
defaultContentLanguage: es
languages:
  es:
    languageName: ES
    weight: 1
  en:
    languageName: EN
    weight: 2
enableEmoji: true
pagination:
  pagerSize: 9
keywords: [website, portfolio, contact]
title: juanddddiego DEV
theme: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
minify:
  disableXML: true
