---
languageCode: en
params:
  DateFormat: January 02, 2006
  profileMode:
    enabled: true
    imageUrl: "/home.png"
    subtitle: I make music
    words: ["make", "compose", "produce", "mix"]
    buttons:
      - identifier: portfolio
        name: Portfolio
        url: "/en/portfolio"
weight: 2
