---
languageCode: es
params:
  DateFormat: January 02, 2006
  label:
    iconHeight: 250;
  profileMode:
    enabled: true
    imageUrl: "/home.gif"
    imageWidth: 350;
    imageHeight: 350;
    subtitle: Hago música
    buttons:
      - identifier: portfolio
        name: Algunos trabajos
        url: "/portfolio"
weight: 1