---
languageCode: en
params:
  DateFormat: January 02, 2006
  label:
    iconHeight: 250;
  profileMode:
    enabled: true
    imageUrl: "/home.png"
    imageWidth: 350;
    imageHeight: 350;
    subtitle: I make music
    buttons:
      - identifier: portfolio
        name: Portfolio
        url: "/en/portfolio"
weight: 2
