---
languageCode: en
languageName: EN
params:
  DateFormat: January 02, 2006
  profileMode:
    enabled: true
    imageUrl: "/home.png"
    imageTitle: "home image"
    buttons:
      - identifier: portfolio
        name: Portfolio
        url: "/en/portfolio"
weight: 2
