---
main:
  - identifier: contact
    name: Envíame tu propuesta
    url: "mailto:hola@juanddddiego.com"
    weight: 10
  - identifier: bookings
    name: Haz una reserva
    pageRef: /bookings
    weight: 20
