---
main:
  - identifier: portfolio
    name: Some projects
    pageRef: /portfolio
    weight: 10
  - identifier: mix-master-portfolio
    name: Mix/Master
    pageRef: /mix-master-portfolio
    weight: 20    
  - identifier: contact
    name: Submit request
    url: "mailto:hola@juanddddiego.com"
    weight: 30
  - identifier: bookings
    name: Book a meeting
    pageRef: /bookings
    weight: 40