---
main:
  - identifier: portfolio
    name: Some projects
    pageRef: /portfolio
    weight: 10
  - identifier: contact
    name: Submit request
    url: "mailto:hola@juanddddiego.com"
    weight: 20
  - identifier: bookings
    name: Book a meeting
    pageRef: /bookings
    weight: 30