author:
  name: Juan Diego Coronel Montesinos
baseURL: "http://jotacoro.github.io/"
defaultContentLanguage: es
languages:
  es:
    languageName: ES
    weight: 1
  en:
    languageName: EN
    weight: 2
enableEmoji: true
keywords: [website, portfolio, contact]
title: juanddddiego
theme: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
minify:
  disableXML: true
